name: Main CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-and-cache

  test:
    name: Run ESLint and Tests
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v4
      - name: Install packages
        uses: ./.github/actions/setup-and-cache
      - name: Run ESLint
        run: npm run lint
      - name: Test
        run: npm test

  build:
    name: Build project
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Install packages
        uses: ./.github/actions/setup-and-cache
      - name: Build project
        id: build-project
        run: npm run build --if-present
      - name: Create artifact for build
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: |
            dist
            !dist/**/*.md
            !dist/**/*.spec.*
