name: Main CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    name: Run ESLint and Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install packages
        id: install
        uses: ./.github/actions/setup-and-cache
      - name: Run ESLint
        if: steps.install.outputs.exit_code == '0'
        run: npm run lint
      - name: Test
        if: steps.install.outputs.exit_code == '0'
        run: npm test

  build:
    name: Build project
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Install packages
        id: install
        uses: ./.github/actions/setup-and-cache
      - name: Build project
        id: build-project
        if: steps.install.outputs.exit_code == '0'
        run: npm run build --if-present
